<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Submission Form</title>
</head>
<body>
    <h1>Employee Submission Form</h1>
    <form id="employeeForm">
        <label for="Name">Name:</label>
        <input type="text" id="Name" name="Name" required><br><br>
        <label for="Email">Email:</label>
        <input type="email" id="Email" name="Email" required><br><br>
        <label for="Department">Department:</label>
        <input type="text" id="Department" name="Department" required><br><br>
        <button type="submit">Submit</button>
    </form>

    <script>
        const form = document.getElementById('employeeForm');
        form.addEventListener('submit', function(e) {
            e.preventDefault();

            const formData = new FormData(form);

            fetch('https://script.google.com/macros/s/AKfycbyegRgneN-ob_k1WZrZUFJwwJtuIa6R7tKbXAMeRKDELwk7isyJ37C5xgOYi4_GmqpZYA/exec', {
                method: 'POST',
                body: formData
            }).then(response => response.json())
              .then(data => {
                  if (data.result === "success") {
                      alert('Form submitted successfully!');
                  } else {
                      alert('There was a problem submitting the form.');
                  }
              }).catch(error => console.error('Error:', error));
        });
    </script>
</body>
</html>

